---
sidebar: sidebar 
permalink: use/report-create.html 
keywords: BlueXP migration reports, volume reports 
summary: BlueXP移行レポートサービスを使用すると、ストレージ環境のファイル、ディレクトリ、シンボリックリンク、ハードリンク、ファイルシステムツリーの深さと幅、大容量ファイルなどの数をすばやく特定できます。 
---
= レポートを作成します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
ボリュームレポートを作成して、ファイル数、ディレクトリ内のファイル数、シンボリックリンク、ハードリンク、最大ファイルサイズ、 その他多数。

レポートを作成するたびに、BlueXP移行レポートサービスがパスをスキャンしてデータを収集します。同じレポート定義を使用して、そのレポートの複数のインスタンスを持つことができます。

BlueXPの移行レポートサービスでは、ボリュームごとにデータが表示されます。

一度に生成できるレポートは1つだけです。

レポートはPDFファイルとしてダウンロードすることもできます。


TIP: BlueXP移行レポートのすべての処理がBlueXPタイムラインに表示されます。タイムラインを表示するには、[BlueXP * Settings]*>*[Timeline]*を選択します。

.手順
. BlueXPの左側のナビゲーションで、*[ストレージ]*>*[移行レポート]*を選択します。
. [新しいレポートの作成]*を選択します。
. レポート名を入力します。
. ドロップダウンリストから作業環境を選択します。
+
作業環境のリストには、BlueXPでアクティブで有効になっている環境だけが表示されます。

+

TIP: データにアクセスするには、BlueXP ConnectorからボリュームのデータLIFにアクセスできる必要があります。

+
環境を有効にする場合は、を参照してください https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-a-connector-is-required["コネクタについては、BlueXPのドキュメントを参照してください"]。

. [検索]*アイコンを使用して、レポートするボリュームを検索するか、リストから選択します。
. ボリュームを選択します。
. [レポートの作成]*を選択します。
+
BlueXP移行レポートサービスは、レポートを生成してレポートリストに表示します。

. レポートを表示するには、[アクション]*... オプションを選択し、*[レポートの表示]*を選択します。
. レポートのPDFファイルをダウンロードするには、[アクション]*... オプションを選択し、*[Download Report]*を選択します。
. 同じレポートの別のインスタンスを生成するには、レポート行を選択し、右側の*レポートの追加*を選択します。

